# Generated by Django 3.2.9 on 2021-11-30 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.IntegerField(default=2018, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='send_email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='send_sms_notification',
            field=models.BooleanField(default=True),
        ),
    ]
