# Generated by Django 3.2.9 on 2021-11-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211130_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='send_email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='send_sms_notification',
            field=models.BooleanField(default=True),
        ),
    ]
