# Generated by Django 3.2.9 on 2021-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='send_email_notification',
            new_name='receive_email_notification',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='send_sms_notification',
            new_name='receive_sms_notification',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
