# Generated by Django 3.2.9 on 2021-12-02 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211202_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
