# Generated by Django 3.2.9 on 2021-12-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_studentprofile_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_mobile_verified',
        ),
    ]
