# Generated by Django 3.2.9 on 2021-11-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211129_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(upload_to='uploads/events/files'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='photo',
            field=models.ImageField(upload_to='uploads/events/images'),
        ),
    ]
