# Generated by Django 3.2.9 on 2021-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_yeartag_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('job_description', models.TextField()),
                ('application_link', models.URLField(blank=True, null=True)),
                ('offer_type', models.CharField(choices=[('I', 'Internship'), ('J', 'Job')], max_length=1)),
                ('application_type', models.CharField(choices=[('OF', 'Off Campus'), ('ON', 'On Campus')], max_length=2)),
                ('year_tags', models.ManyToManyField(related_name='job', to='core.YearTag')),
            ],
        ),
    ]
