# Generated by Django 3.2.9 on 2021-12-05 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
