# Generated by Django 3.2.9 on 2021-11-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeartag',
            name='year',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
