# Generated by Django 3.2.9 on 2021-11-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticeClass',
            new_name='Notice',
        ),
    ]
