# Generated by Django 3.2.9 on 2021-11-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_yeartag_year'),
        ('notices', '0003_auto_20211128_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='tags',
            field=models.ManyToManyField(related_name='year_tags', to='core.YearTag'),
        ),
    ]
